config/routes.rb
Rails.application.routes.draw do

	get "home" => "static_pages#home", as: "home"

	get "resume" => "static_pages#resume", as: "resume"

	get "coming_soon" => "static_pages#coming_soon", as: "coming_soon"

	get "springboot" => "projects#springboot", as: "springboot"

	get "rubyonrails" => "projects#rubyonrails", as: "rubyonrails"

	get "visualbasic" => "projects#visualbasic", as: "visualbasic"

	get "projects" => "static_pages#projects", as: "projects"

	get "aboutme" => "static_pages#aboutme", as: "aboutme"

	root 'static_pages#home'

	get 'download_resume', to: 'downloads#download_resume'

	get 'contact-me', to: 'messages#new', as: 'new_message'
	post 'contact-me', to: 'messages#create', as: 'create_message'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
	include ActiveModel::Model
    attr_accessor :name, :email, :body
    validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
	def download_resume
		send_file "#{Rails.root}/app/assets/downloads/resume.pdf", type: "application.pdf", x_sendfile: true
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
	end

	def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to messages_new_url, notice: "Message received"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def springboot
  end

  def rubyonrails
  end

  def visualbasic
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def projects
  end

  def resume
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustinPauga</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body class="container">
  <nav>
    
      <div class="navbar">
       <%= image_tag("/Logo.PNG", class: "logo") %> 
       <%= link_to "Home", home_path %>
       <div class="dropdown">
          <%= link_to "Projects", projects_path %>
          <div class="dropdown-content">
            <%= link_to "Spring Boot", springboot_path %>
            <%= link_to "Ruby on Rails", rubyonrails_path %>
            <%= link_to "Visual Basic", visualbasic_path %>
          </div>
       </div>     
      <%= link_to "Resume", resume_path %>
      <%= link_to "Contact", coming_soon_path, style: "float: right" %>
      <%= link_to "About me", aboutme_path, style: "float: right" %>
      </div>
    
  </nav>
    
    <%= yield %>
</body>
<footer>
<hr>
    <h2 style="text-align: center">Feel free to contact me directly!</h2>

    <!-- Social media and contact links. -->
    <div class="socialbtns" style="text-align: center">
      <a href="mailto:paugajt@gmail.com" target="_blank">paugajt@gmail.com</a>
      <p>My LinkedIn Profile can be found <a href="https://www.linkedin.com/in/justin-pauga-51152698/" target="_blank">Here</a> | My Github Repositories can be found <a href="https://github.com/paugajt" target="_blank">Here</a></p>
      
    </div>
    <p style="text-align: center">Copyright 2017 by Justin Pauga</p>
</footer>
</html>

app/views/messages/new.html.erb
<h1 class="heading">Contact me</h1>

<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <p class="contact">Name: <%= f.text_field :name, placeholder: 'name' %></p>
  <p class="contact">Email:<%= f.email_field :email, placeholder: 'email' %></p>
  <p class="contact">Message:<%= f.text_area :body, placeholder: 'body' %></p>
  <p class="contact"><%= f.submit 'Send' %></p>
<% end %>

app/views/projects/rubyonrails.html.erb
<main>
	<h1 class="heading">Ruby on Rails Web Application</h1>
  
  <p class="projects-text">Database web application built using Ruby on Rails, HTML and CSS. The application stores professors and students as well as courses and sections. Functionality includes the ability to assign sections to a course and a professor.</p>

  <p style="text-align: center"><%= image_tag("/rails.PNG", id: "rubyonrails") %></p>

  <p style="text-align: center">See the source code here: <a href="https://github.com/paugajt/WebApp" target="_blank">Github Repo</a></p>

</main>

app/views/projects/springboot.html.erb
<main>
	<h1 class="heading">Spring Boot Web Application</h1>
  
  <p class="projects-text" style="text-align: center">Database web application built using Spring Boot framework, Java, HTML, and CSS. Developed using Agile development techniques with my Scrum group, RebelScrum.</p>




  <p style="text-align: center"><%= image_tag("/springboot.PNG", id: "springboot") %></p>

  <p class="projects-text">This application stores users as professors, students or administrators. It also keeps track of courses, sections, buildings and classrooms. Functionality includes creating a schedule based on a semester and year as well as assigning professors to a section of a course and allowing students to sign up for sections.</p>

    
  <p style="text-align: center">See the app in action here: <a href="https://rebelscrum.herokuapp.com" target="_blank">Heroku App</a> | See the source code here: <a href="https://github.com/paugajt/RebelScrumBannerProject" target="_blank">Github Repo</a></p>
</main>

app/views/projects/visualbasic.html.erb
<main>
	<h1 class="heading">Visual Basic Vending Machine</h1>

	<p class="projects-text"> Windows application built using Visual Basic .NET.</p>

	<p style="text-align: center"><%= image_tag("/vendingMachineHome.PNG", id: "visualbasic") %></p>

	<p class="projects-text"> A functional Vending machine that allows a user to select up to five items for an order, "input" money and receive change as well as their items. Includes a manager mode that allows a manager to log in, update inventory, generate a sales report, generate an inventory report and pull out the daily profit.</p>

	<p style="text-align: center">You can see the source code here: <a href="https://github.com/paugajt/VB-Vending-Machine" target="_blank">Github</a></p>

app/views/static_pages/aboutme.html.erb
<main>
	<h3 style="text-align: center"><i>Learn about who I am aside from being a software engineering student</i></h3>
	<p style="text-align: center"><%= image_tag("/rugby.jpg", class: "img-circle", id: "aboutme-top") %></p>
	<h1 class="heading">MY PASSIONS AND PERSONALITY</h1>

	<p class="about-me-text"> For the last 15 years my passion has been rugby. I have played primarily for the Glendale Raptors with a brief stint with Denver Barbarians as well as playing college rugby at Colorado State University.</p>

	<p class="about-me-text">Throughout my rugby career, I have been fortunate to have played alongside some of the best players in America as well as being coached by some of the greatest players in the world. </p>

	<p class="about-me-text">Rugby has allowed me to travel all over the United States and has taught me the value of hard work, discipline and teamwork.</p>

	
	<h2 class="accolades">Accolades:</h2>
	<div class="about-me-accolades">
		<ul>
			<li>ERFU Select Side - High School | 2004</li>
			<li>KUDU Select Side | 2006</li>
			<li>ERFU Select Side - College | 2006</li>
			<li>Selects 7's | 2015</li>
			<li>2014 All PRP Team</li>
			<li>Glendale Raptors<ul>
					<li>2011 National Champions</li>
					<li>2015 & 2016 PRP Champions</li>
				</ul></li>
		</ul>
	</div>

app/views/static_pages/coming_soon.html.erb
<br>
<br>
<br>
<h1 style="font-weight: bold; text-align: center; color: white; font-size: 400%">Coming Soon!</h1>

app/views/static_pages/home.html.erb
<h1 class="heading" id="homename">Justin Pauga</h1>
    <p style="text-align: center"><%= image_tag ("Signature.png"), class: "img-circle" %></p>

    <div style="margin: 0% 15% 0% 15%">
    <p style="text-align: center">I am a software engineering student with a passion for learning and writing code. I have a strong knowledge of object-oriented programming and application development tools. Consistently commended by professors and classmates for programming abilities, grasp of multiple technologies and attention to detail. Known as a self-starter, multitasker and team player who strives to consistently exceed expectations.</p>
</div>
</main>

app/views/static_pages/projects.html.erb
<main>
  <h1 class="heading">Programming Projects</h1>
  <p style="text-align: center"><%= image_tag("/coding.jpg", class: "projects-img") %></p>
  <hr>

  <h2 class="heading"><%= link_to "Spring Boot Web Application", springboot_path %></h2>
  <p style="text-align: center"><%= image_tag("/springboot.PNG", class: "projects-img") %></p>
  
<hr>

  <h2 class="heading"><%= link_to "Ruby on Rails Web Application", rubyonrails_path %></h2>
  <p style="text-align: center"><%= image_tag("/rails.PNG", class: "projects-img") %></p>
  
  
<hr>

  <h2 class="heading"><%= link_to "Visual Basic Vending Machine", visualbasic_path %></h2>

</main>

app/views/static_pages/resume.html.erb
<main id="resume">
        <p style="text-align: center"><%= image_tag ("Signature.png"), class: "img-circle" %></p>
        
        <h2 class="heading">Software Engineering Student</h2>
        <p style="text-align: center">You can download a PDF version of my full resume: <%= link_to "Here", download_resume_path%></p>
        <hr>

        <h2 class="resume-section-center">Education</h2>
        <hr>
        <div id="school_info">
          <b>Baccalaureate of Science | Computer Science | Mathematical Science Minor</b>
          <p>Metropolitan State University of Denver | Denver, Colorado</p>
          <p> Graduation | December 2018</p>
        </div>
        <hr>
        <h2 class="resume-section">Skill Highlights</h2>
        <hr>
        <div class="info" id="skills">
          <ul class="col">
            <li>Agile/Scrum Methodology</li>
            <li>Java</li>
            <li>Spring Boot</li>
            <li>Visual Basic .NET</li>
            <li>Ruby</li>
            <li>Ruby on Rails</li>
            <li>Javascript</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>Bootstrap</li>
            <li>SQL</li>
            <li>Git & Github</li>
            <li>SAP</li>
            <li>Microsoft Office (Word, Excel, Access)</li>
          </ul>
        </div>
        <hr>
        <h2 class="resume-section">Experience</h2>
          <hr>
          <div class="info">
          <p class="resume-info">IT Manager<span class="job-date">September 2017 - Present</span></p>
          <p class="resume-info">Walls By Design</p>
          <p class="resume-text-body">Responsible for the design, build, and implementation of a new CRM and DBMS to fit current company needs and to be scalable as the company grows. Also responsible for general IT and program issues within the company.</p>
          <hr>
          <p class="resume-info">Computer Lab Technician<span class="job-date">August 2016 - Present</span></p>
          <p class="resume-info">Metropolitan State University of Denver</p>
          <p class="resume-text-body">Monitor for the campus computer lab and assisting students with technical issues. Responsible for trouble shooting various issues including server connection problems, hardware issues, running scripts and assisting students with program issues and connecting with the printers.</p> 
          <hr>
          <p class="resume-info">Professional Athlete<span class="job-date">January 2016 - August 2017</span></p>
          <p class="resume-info">ProRugby North America | Glendale Raptors</p>
          <p class="resume-text-body">Contracted player in the first professional rugby league in America. Responsible for daily meetings, workouts and practice sessions as well as competing for the Denver team on the weekends.  Also responsible for participation in media and sponsor-related activities and interviews. This position required strong teamwork skills, dedication, motivation, excellent decision making skills, an understanding of excellence and high-performance as well as the ability to perform under pressure.</p>
          <hr>
          <p class="resume-info">Heavy Equipment Operator | Supervisor<span class="job-date">March 2014 - January 2016</span></p>
          <p class="resume-info">Gilbert Contracting Inc</p>
          <p class="resume-text-body">Began as a laborer, was promoted to heavy equipment operator and then became supervisor. Responsible for managing and supervising laborers and operators on a job site to ensure all safety procedures were being followed while completing job assignments on time. Job assignments included digging foundations, installing drainage infrastructure, as well as grading earth for concrete and asphalt.  Also responsible for reading blueprints, calculating elevation measurements and using engineering tools in the field.</p>
        </div>
        <hr>
        <h2 class="resume-section-center">Additional Experience</h2>
        <hr>
        <div class="info" id="exp-add">
          <ul class="exp-col">
            <li>Nike | 2013-2014</li>
            <li>Denver Water | 2010-2012</li>
            <li>Anheuser Busch | 2008-2010</li>
            <li>City of Wheat Ridge | 2004-2007</li>
          </ul>
        </div>


</main>